// packages/react-ui/src/components/progress.tsx
"use client"

import * as React from "react"
import * as ProgressPrimitive from "@radix-ui/react-progress"

import { cn } from "../lib/utils"

function Progress({
  className,
  value,
  ...props
}: React.ComponentProps<typeof ProgressPrimitive.Root>) {
  return (
    <ProgressPrimitive.Root
      data-slot="progress"
      className={cn(
        "bg-primary/20 relative h-3 w-full overflow-hidden rounded-full",
        className
      )}
      {...props}
    >
      <ProgressPrimitive.Indicator
        data-slot="progress-indicator"
        className="bg-primary h-full w-full flex-1 transition-colors"
        style={{ transform: `translateX(-${100 - (value || 0)}%)` }}
      />
    </ProgressPrimitive.Root>
  )
}

export { Progress }

// packages/nuxt-ui/src/components/Progress.vue
<script setup lang="ts">
import { ProgressRoot, ProgressIndicator } from "reka-ui"
import { cn } from "../lib/utils"

interface Props {
  class?: string
  modelValue?: number
}
const props = defineProps<Props>()
</script>
<template>
  <ProgressRoot data-slot="progress" :model-value="modelValue" :class="cn('bg-primary/20 relative h-3 w-full overflow-hidden rounded-full', props.class)">
    <ProgressIndicator
      data-slot="progress-indicator"
      class="bg-primary h-full w-full flex-1 transition-colors"
      :style="{ transform: `translateX(-${100 - (modelValue || 0)}%)` }"
    />
  </ProgressRoot>
</template>
