// packages/react-ui/src/components/questions-card.tsx
'use client';

import * as React from 'react';
import { MessageSquare, ChevronDown } from 'lucide-react';
import { cn } from '../lib/utils';
import { Collapsible, CollapsibleTrigger, CollapsibleContent } from './collapsible';
import { Button } from './button';

export interface QuestionsCardItem {
  question: React.ReactNode;
  answer: string;
}

export interface QuestionsCardProps {
  items: QuestionsCardItem[];
  defaultExpanded?: boolean;
  className?: string;
}

/** Collapsible summary of answered questions — bordered card with an answered-count trigger. */
function QuestionsCard({ items, defaultExpanded = false, className }: QuestionsCardProps) {
  const [expanded, setExpanded] = React.useState(defaultExpanded);
  const answeredCount = items.filter((i) => i.answer).length;

  return (
    <Collapsible open={expanded} onOpenChange={setExpanded}>
      <div className={cn('rounded-2xl border border-border/40 bg-muted/20 overflow-hidden', className)}>
        <CollapsibleTrigger asChild>
          <Button
            type="button"
            variant="ghost"
            className="flex items-center gap-1.5 w-full px-2.5 py-1.5 h-auto text-left rounded-none justify-start hover:bg-muted/40"
          >
            <MessageSquare className="size-3.5 text-muted-foreground shrink-0" />
            <span className="text-xs font-medium text-foreground">Questions</span>
            <span className="text-xs text-muted-foreground/70">{answeredCount} answered</span>
            <ChevronDown
              className={cn('size-3 text-muted-foreground ml-auto transition-transform', expanded && 'rotate-180')}
            />
          </Button>
        </CollapsibleTrigger>
        <CollapsibleContent>
          <div className="border-t border-border/30">
            {items.map((item, i) => (
              <div key={i} className="px-2.5 py-2 border-b border-border/30 last:border-b-0">
                <div className="text-xs text-muted-foreground/70 leading-relaxed">{item.question}</div>
                <div className="text-sm font-medium text-foreground mt-0.5">{item.answer || 'No answer'}</div>
              </div>
            ))}
          </div>
        </CollapsibleContent>
      </div>
    </Collapsible>
  );
}

export { QuestionsCard };

// packages/nuxt-ui/src/components/QuestionsCard.vue
<script setup lang="ts">
import { ref, computed } from "vue"
import { MessageSquare, ChevronDown } from "lucide-vue-next"
import { cn } from "../lib/utils"
import Collapsible from "./Collapsible.vue"
import CollapsibleTrigger from "./CollapsibleTrigger.vue"
import CollapsibleContent from "./CollapsibleContent.vue"
import Button from "./Button.vue"

export interface QuestionsCardItem {
  question: string
  answer: string
}

interface Props {
  items: QuestionsCardItem[]
  defaultExpanded?: boolean
  class?: string
}
const props = withDefaults(defineProps<Props>(), { defaultExpanded: false })
const expanded = ref(props.defaultExpanded)
const answeredCount = computed(() => props.items.filter((i) => i.answer).length)
</script>
<template>
  <Collapsible v-model:open="expanded">
    <div :class="cn('rounded-2xl border border-border/40 bg-muted/20 overflow-hidden', props.class)">
      <CollapsibleTrigger as-child>
        <Button type="button" variant="ghost" class="flex items-center gap-1.5 w-full px-2.5 py-1.5 h-auto text-left rounded-none justify-start hover:bg-muted/40">
          <MessageSquare class="size-3.5 text-muted-foreground shrink-0" />
          <span class="text-xs font-medium text-foreground">Questions</span>
          <span class="text-xs text-muted-foreground/70">{{ answeredCount }} answered</span>
          <ChevronDown :class="cn('size-3 text-muted-foreground ml-auto transition-transform', expanded && 'rotate-180')" />
        </Button>
      </CollapsibleTrigger>
      <CollapsibleContent>
        <div class="border-t border-border/30">
          <div v-for="(item, i) in items" :key="i" class="px-2.5 py-2 border-b border-border/30 last:border-b-0">
            <div class="text-xs text-muted-foreground/70 leading-relaxed">{{ item.question }}</div>
            <div class="text-sm font-medium text-foreground mt-0.5">{{ item.answer || 'No answer' }}</div>
          </div>
        </div>
      </CollapsibleContent>
    </div>
  </Collapsible>
</template>
