// packages/react-ui/src/components/submit-button.tsx
'use client';

import * as ReactDOM from 'react-dom';
import * as React from 'react';
import { type ComponentProps } from 'react';

const useFormStatus = (ReactDOM as any).useFormStatus as () => {
  pending: boolean;
  action: ((formData: FormData) => void | Promise<void>) | null;
};
const useActionState = (React as any).useActionState as <S>(
  action: (state: S, formData: FormData) => Promise<S>,
  initialState: S,
) => [S, (formData: FormData) => void];
import { Button } from './button';
import { Alert, AlertDescription } from './alert';
import { AlertTriangle } from 'lucide-react';

type Props = Omit<ComponentProps<typeof Button>, 'formAction'> & {
  pendingText?: string;
  formAction: (prevState: any, formData: FormData) => Promise<any>;
  errorMessage?: string;
};

const initialState = {
  message: '',
};

export function SubmitButton({
  children,
  formAction,
  errorMessage,
  pendingText = 'Submitting...',
  ...props
}: Props) {
  const { pending, action } = useFormStatus();
  const [state, internalFormAction] = useActionState(formAction, initialState);

  const isPending = pending && action === internalFormAction;

  return (
    <div className="flex flex-col gap-y-4 w-full">
      {Boolean(errorMessage || state?.message) && (
        <Alert variant="destructive" className="w-full">
          <AlertTriangle className="h-4 w-4" />
          <AlertDescription>{errorMessage || state?.message}</AlertDescription>
        </Alert>
      )}
      <div>
        <Button
          {...props}
          type="submit"
          aria-disabled={pending}
          formAction={internalFormAction as unknown as string}
        >
          {isPending ? pendingText : children}
        </Button>
      </div>
    </div>
  );
}

// packages/nuxt-ui/src/components/SubmitButton.vue
<script setup lang="ts">
import { AlertTriangle } from "lucide-vue-next"
import Button from "./Button.vue"
import Alert from "./Alert.vue"
import AlertDescription from "./AlertDescription.vue"
import type { ButtonVariants } from "./button"

interface Props {
  pending?: boolean
  pendingText?: string
  errorMessage?: string
  variant?: ButtonVariants["variant"]
  size?: ButtonVariants["size"]
}
withDefaults(defineProps<Props>(), { pendingText: "Submitting..." })
</script>

<template>
  <div class="flex flex-col gap-y-4 w-full">
    <Alert v-if="errorMessage" variant="destructive" class="w-full">
      <AlertTriangle class="h-4 w-4" />
      <AlertDescription>{{ errorMessage }}</AlertDescription>
    </Alert>
    <div>
      <Button type="submit" :variant="variant" :size="size" :aria-disabled="pending" :disabled="pending">
        <slot v-if="!pending" />
        <template v-else>{{ pendingText }}</template>
      </Button>
    </div>
  </div>
</template>
