// packages/ui/src/components/Label.vue
<script setup lang="ts">
import { Label as LabelPrimitive } from "reka-ui"
import { cn } from "../lib/utils"

const props = defineProps<{ class?: string }>()
</script>

<template>
  <LabelPrimitive
    data-slot="label"
    :class="cn(
      'cursor-pointer flex items-center gap-2 text-sm leading-none font-medium select-none group-data-[disabled=true]:pointer-events-none group-data-[disabled=true]:opacity-50 peer-disabled:cursor-not-allowed peer-disabled:opacity-50',
      props.class
    )"
  >
    <slot />
  </LabelPrimitive>
</template>

// packages/react-ui/src/components/label.tsx
"use client"

import * as React from "react"
import * as LabelPrimitive from "@radix-ui/react-label"

import { cn } from "../lib/utils"

function Label({
  className,
  ...props
}: React.ComponentProps<typeof LabelPrimitive.Root>) {
  return (
    <LabelPrimitive.Root
      data-slot="label"
      className={cn(
        "cursor-pointer flex items-center gap-2 text-sm leading-none font-medium select-none group-data-[disabled=true]:pointer-events-none group-data-[disabled=true]:opacity-50 peer-disabled:cursor-not-allowed peer-disabled:opacity-50",
        className
      )}
      {...props}
    />
  )
}

export { Label }
