// packages/nuxt-ui/src/components/Skeleton.vue
<script setup lang="ts">
import { cn } from "../lib/utils"
const props = defineProps<{ class?: string }>()
</script>

<template>
  <div
    :class="cn(
      'relative overflow-hidden rounded-2xl',
      'bg-gradient-to-r from-primary/10 via-primary/5 to-primary/10',
      'skeleton-animate',
      props.class
    )"
  >
    <div class="skeleton-shimmer-wrapper">
      <div class="skeleton-shimmer-bar" />
    </div>
  </div>
</template>

// packages/react-ui/src/components/skeleton.tsx
'use client';

import { cn } from '../lib/utils';
import React from 'react';

function Skeleton({
  className,
  ...props
}: React.HTMLAttributes<HTMLDivElement>) {
  return (
    <div
      className={cn(
        'relative overflow-hidden rounded-2xl',
        'bg-gradient-to-r from-primary/10 via-primary/5 to-primary/10',
        'skeleton-animate',
        className,
      )}
      {...props}
    >
      <div className="skeleton-shimmer-wrapper">
        <div className="skeleton-shimmer-bar" />
      </div>
    </div>
  );
}

export { Skeleton };
